### PR TITLE
Fix #3 - work with repos that has depth defined

### LINKED ISSUE #3: It fails if git fetch with depth set
If fetching with depth set, as some CI servers do (ex: Codeship)...

```
git clone --depth 50 git@github.com:user/repository.git
```

It fails with...
```
/home/rof/cache/bundler/ruby/2.3.0/gems/pronto-0.7.1/lib/pronto/git/repository.rb:72:in `merge_base': Revspec 'origin/develop' not found. (Rugged::ReferenceError)
	from /home/rof/cache/bundler/ruby/2.3.0/gems/pronto-0.7.1/lib/pronto/git/repository.rb:72:in `merge_base'
	from /home/rof/cache/bundler/ruby/2.3.0/gems/pronto-0.7.1/lib/pronto/git/repository.rb:15:in `diff'
	from /home/rof/cache/bundler/ruby/2.3.0/gems/pronto-0.7.1/lib/pronto.rb:54:in `run'
	from /home/rof/cache/bundler/ruby/2.3.0/gems/pronto-0.7.1/lib/pronto/cli.rb:54:in `block in run'
	from /home/rof/cache/bundler/ruby/2.3.0/gems/pronto-0.7.1/lib/pronto/cli.rb:53:in `chdir'
	from /home/rof/cache/bundler/ruby/2.3.0/gems/pronto-0.7.1/lib/pronto/cli.rb:53:in `run'
```

It's related with this line at runner.rb:
```ruby
merge_base = @repo.merge_base(commit, commit) # HACK: to make refs work
```

I'm already working on a fix. PR soon.

cc: @mmozuras

### PR DESCRIPTION
**Pull request by abinoam**
See #3 for details.
- Add specs for the current behavior
- Fix the depth problem while maintaining current behavior

Dear @mmozuras,

I have already bumped up the version to 0.1.4 in case you merge and release soon.

### CODE REVIEW

**Comment by mmozuras** [comment]
@abinoam could you rebase on `master`? I've removed support for ruby 1.9.3, should fix the failing build.

**Comment by mmozuras** [comment]
@abinoam could you also squash some of the commits using interactive rebase?

For example:  `f1fa226` and `fd19305`. I understand that it's convenient for development, but when merged to master, specs should ideally pass after every commit in history 😄 

Other than that, looks good 👍

**Comment by abinoam** [comment]
Hi @mmozuras did I get right the rebase/squash suggestion?
Travis passing ok now.

**Comment by mmozuras** [comment]
@abinoam perfect! 😄

**Comment by abinoam** [comment]
Hi @mmozuras, after this fix, the pronto-poper failed deeper in the code with ``` Rugged::OdbError: Object not found - no match for id```. I have tried to work around it, but was not able to solve. It was easier for me to fix the repository and don't fight with this.

The trick is to run a fetch with --unshallow before running pronto, so it fetches the whole commit history. Then rugged will not complain about it.

```
git fetch origin develop:develop --unshallow
pronto run -c develop -f github
```

Now that everything is working I have written a blog post about it.

[Pronto, Codeship and GitHub for automatic code review](http://abinoam.tl1n.com/pronto-codeship-and-github-for-automatic-code-review/)

Sorry for writing in a closed issue, but I thought it could be useful for anyone trying to run pronto and getting this weird ```Rugged::OdbError```.

**Pull request merged**
